spring.application.name=crud
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=felespipes31

spring.jpa.propertis.hibernate.dialect=org.hibernate.MySQLDialect
spring.jpa.hibernate.ddl-auto=update